Update update-submodules.yml

diff --git a/.github/workflows/update-submodules.yml b/.github/workflows/update-submodules.yml
--- a/.github/workflows/update-submodules.yml
+++ b/.github/workflows/update-submodules.yml
@@ -1,43 +1,43 @@
----
-name: Update submodules!
+name: Update Submodules
 
-#############################
-# Start the job on all push #
-#############################
 on:
-  schedule:
-    - cron: "0 0 */7 * *"
   workflow_dispatch:
 
-###############
-# Set the Job #
-###############
 jobs:
-  build:
-    name: Update submodules
+  update-submodules:
     runs-on: ubuntu-latest
-    env:
-      PARENT_REPOSITORY: 'qnblackcat/uYouPlus'
-      CHECKOUT_BRANCH: 'main'
-      PR_AGAINST_BRANCH: 'main'
-      OWNER: 'qnblackcat'
 
     steps:
-      ##########################
-      # Checkout the code base #
-      ##########################
-      - name: Checkout Code
-        uses: actions/checkout@v3
+      - name: Checkout code
+        uses: actions/checkout@v3.5.3
 
-      ####################################
-      # Run the action against code base #
-      ####################################
-      - name: run action
-        id: run_action
-        uses: qnblackcat/github-action-create-pr-parent-submodule@main
-        with:
-          github_token: ${{ secrets.RELEASE_HUB_SECRET }}
-          parent_repository: ${{ env.PARENT_REPOSITORY }}
-          checkout_branch: ${{ env.CHECKOUT_BRANCH }}
-          pr_against_branch: ${{ env.PR_AGAINST_BRANCH }}
-          owner: ${{ env.OWNER }}
+      - name: Set up Git
+        run: |
+          git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
+          git config --global user.name "arichorn"
+
+      - name: Add uYouPlusExtra submodules
+        run: |
+          git submodule add https://github.com/PoomSmart/YouMute.git Tweaks/YouMute
+          git submodule add https://github.com/PoomSmart/YouQuality.git Tweaks/YouQuality
+          git submodule add https://github.com/PoomSmart/YTVideoOverlay.git Tweaks/YTVideoOverlay
+          git submodule add https://github.com/arichorn/YTNoCommunityPosts.git Tweaks/YTNoCommunityPosts
+          git add .
+          git commit -m "added uYouPlusExtra submodules"
+          git push origin
+
+      - name: Update submodules
+        run: |
+          git submodule update --init --recursive --remote
+          git add .
+          git commit -m "updated submodules"
+          git push origin
+        continue-on-error: true
+
+      - name: Check exit code
+        run: |
+          exit_code=$?
+          if [ $exit_code -ne 0 ]; then
+            echo "Submodule update failed with exit code $exit_code"
+            exit 1
+          fi
